language: node_js

node_js:
  - 6

script:
  - npm start

before_install:
  - sudo apt-get install make
  - sudo apt-get install g++
  - sudo apt-get install python
  - sudo npm install node-gyp -g

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
    
services:
  mongodb
