language: node_js

node_js:
  - 6
before_script:
  - sudo npm install node-gyp -g

script:
  - npm start

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install make g++ python -y

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
    
services:
  mongodb
