language: node_js

node_js:
  - 6

script:
  - npm start

before_install:
  - npm install -g webpack

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
    
services:
  mongodb
